version: '3.5'
services:
  web:
    container_name: gvstorage-react-ssr-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
      - '35729:35729'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
            
