export const ACTIONTYPES = {
    'PROFILE': {
        SET_CURRENT_PROFILE : 'auth/SET_CURRENT_PROFILE'
    },
    'HOME':{
        GET_ALL_DISCOUNTS: 'GET_ALL_DISCOUNTS',
        GET_ALL_PINCODES: 'GET_ALL_PINCODES',
        GET_ALL_SITES: 'GET_ALL_SITES',
        GET_ALL_PINCODES_SITES: 'GET_ALL_PINCODES_SITES'
    },
    'SEARCH': {
        GET_ALL_SITES_BY_FILTER: 'GET_ALL_SITES_BY_FILTER',
        GET_ALL_SITES_BY_CHECKBOXES: 'GET_ALL_SITES_BY_CHECKBOXES',
        RESET_ALL_SITES_BY_FILTER:'RESET_ALL_SITES_BY_FILTER'
    },
    'SELF_STORAGE':{
        GET_ALL_UNITS_LOCATION_CODE: 'GET_ALL_UNITS_LOCATION_CODE',
        RESET_SELF_STORAGE_ALL_UNITS:'RESET_SELF_STORAGE_ALL_UNITS'
    },
    'RESERVE':{
        GET_ALL_MOVEIN_CHARGES: 'GET_ALL_MOVEIN_CHARGES',
        GET_SELECTED_UNIT_INFO: 'GET_SELECTED_UNIT_INFO'
    },
    'SHARED': {
        GET_FILTER_INFO: 'GET_FILTER_INFO'
    }
}