export const Environment = {
    MW_END_POINT_URL : process.env.REACT_APP_API_ENDPOINT,
    STATIC_FILES_END_POINT_URL: process.env.REACT_APP_STATIC_FILE_URL,
    GOOGLE_MAP_KEY: process.env.REACT_APP_GOOGLE_MAP_KEY, 
    IP_STACK_ENDPOINT: process.env.REACT_APP_IP_STACK_ENDPOINT
}